# Generated by Django 4.1 on 2022-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='email',
            field=models.EmailField(default='email@provider.com', max_length=254),
        ),
        migrations.AddField(
            model_name='studentform',
            name='fullname',
            field=models.CharField(default='William Bonner', max_length=200),
        ),
        migrations.AddField(
            model_name='studentform',
            name='mobile_number',
            field=models.FloatField(default='000000000'),
        ),
        migrations.AlterModelTable(
            name='studentform',
            table=None,
        ),
    ]
